<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
	<PackageIcon>nova.ico</PackageIcon>
	<RepositoryUrl>https://github.com/IcyDrae/Nova</RepositoryUrl>
	<ApplicationIcon>Assets\nova.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\nova.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\nova.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="Assets\nova.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
	
</Project>
